# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(542, 352)
        self.label = QtWidgets.QLabel(Window)
        self.label.setGeometry(QtCore.QRect(10, 10, 51, 16))
        self.label.setObjectName("label")
        self.dirEdit = QtWidgets.QLineEdit(Window)
        self.dirEdit.setGeometry(QtCore.QRect(10, 30, 441, 20))
        self.dirEdit.setReadOnly(True)
        self.dirEdit.setObjectName("dirEdit")
        self.loadFilesButton = QtWidgets.QPushButton(Window)
        self.loadFilesButton.setGeometry(QtCore.QRect(460, 30, 75, 23))
        self.loadFilesButton.setObjectName("loadFilesButton")
        self.label_4 = QtWidgets.QLabel(Window)
        self.label_4.setGeometry(QtCore.QRect(10, 270, 81, 16))
        self.label_4.setObjectName("label_4")
        self.prefixEdit = QtWidgets.QLineEdit(Window)
        self.prefixEdit.setGeometry(QtCore.QRect(10, 290, 441, 20))
        self.prefixEdit.setReadOnly(False)
        self.prefixEdit.setObjectName("prefixEdit")
        self.renameFilesButton = QtWidgets.QPushButton(Window)
        self.renameFilesButton.setGeometry(QtCore.QRect(460, 290, 75, 23))
        self.renameFilesButton.setObjectName("renameFilesButton")
        self.progressBar = QtWidgets.QProgressBar(Window)
        self.progressBar.setGeometry(QtCore.QRect(10, 320, 521, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.splitter_3 = QtWidgets.QSplitter(Window)
        self.splitter_3.setGeometry(QtCore.QRect(10, 60, 512, 205))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setObjectName("label_2")
        self.srcFilesList = QtWidgets.QListWidget(self.splitter)
        self.srcFilesList.setObjectName("srcFilesList")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label_3 = QtWidgets.QLabel(self.splitter_2)
        self.label_3.setObjectName("label_3")
        self.dstFilesList = QtWidgets.QListWidget(self.splitter_2)
        self.dstFilesList.setObjectName("dstFilesList")

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "File renamer"))
        self.label.setText(_translate("Window", "Directory:"))
        self.loadFilesButton.setText(_translate("Window", "&Load files"))
        self.label_4.setText(_translate("Window", "Filename prefix:"))
        self.prefixEdit.setText(_translate("Window", "Rename your files to..."))
        self.renameFilesButton.setText(_translate("Window", "&Rename"))
        self.label_2.setText(_translate("Window", "File to rename"))
        self.label_3.setText(_translate("Window", "Renamed files"))
